spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_spring
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


